MantenimientosBundle\Entity\Agencia:
    type: entity
    table: agencia
    id:
        codigoAgencia:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigo_agencia
            generator:
                strategy: IDENTITY
    fields:
        nombreAgencia:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: nombre_agencia
        telefono:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        descripcion:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
