MantenimientosBundle\Entity\Empleados:
    type: entity
    table: empleados
    id:
        codigoEmpleado:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigo_empleado
            generator:
                strategy: IDENTITY
    fields:
        nombres:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        apellidos:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        dui:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
        direccion:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        telefono:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
    lifecycleCallbacks: {  }
