MantenimientosBundle\Entity\Proveedor:
    type: entity
    table: proveedor
    id:
        codigoProveedor:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigo_proveedor
            generator:
                strategy: IDENTITY
    fields:
        nombreProveedor:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: nombre_proveedor
        telefono:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        contacto:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
